# Generated by Django 5.1 on 2025-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('location', models.TextField(max_length=1000)),
                ('no_of_tables', models.IntegerField()),
            ],
        ),
    ]
