# Generated by Django 5.2 on 2025-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_tag_restauranttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttags',
            name='icon',
            field=models.ImageField(blank=True, default='food-icon.png', upload_to=''),
        ),
    ]
