# Generated by Django 5.2 on 2025-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restauranttags_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttags',
            name='icon',
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, default='food-icon.png', upload_to=''),
        ),
    ]
