# Generated by Django 5.2 on 2025-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='no_of_guests',
            field=models.IntegerField(default=1),
        ),
    ]
