# Generated by Django 5.2 on 2025-04-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_no_of_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=2000)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.reservation')),
            ],
        ),
    ]
